#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <ctype.h> /* For isspace, isxdigit */



const char* redhat_ascii[] = {
         "#EE0000",
         "           .MMM..:MMMMMMM                ",
         "          MMMMMMMMMMMMMMMMMM             ",
         "          MMMMMMMMMMMMMMMMMMMM.          ",
         "         MMMMMMMMMMMMMMMMMMMMMM          ",
         "        ,MMMMMMMMMMMMMMMMMMMMMM:         ",
         "        MMMMMMMMMMMMMMMMMMMMMMMM         ",
         "  .MMMM'  MMMMMMMMMMMMMMMMMMMMMM         ",
         " MMMMMM    `MMMMMMMMMMMMMMMMMMMM.        ",
         "MMMMMMMM      MMMMMMMMMMMMMMMMMM .       ",
        "MMMMMMMMM.       `MMMMMMMMMMMMM' MM.      ",
        "MMMMMMMMMMM.                     MMMM    ",
        "`MMMMMMMMMMMMM.                 ,MMMMM.  ",
        " `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM. ",
        "    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ",
        "      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM: ",
        "         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  ",
        "            `MMMMMMMMMMMMMMMMMMMMMMMM:   ",
        "                ``MMMMMMMMMMMMMMMMM'     ",
        NULL
};

const char *arch_ascii[] = {
	"#00FFFF",
	"                  ▟█▙                     ",
	"                 ▟███▙                    ",
	"                ▟█████▙                   ",
	"               ▟███████▙                  ",
	"              ▂▔▀▜██████▙                 ",
	"             ▟██▅▂▝▜█████▙                ",
	"            ▟█████████████▙               ",
	"           ▟███████████████▙              ",
	"          ▟█████████████████▙             ",
	"         ▟███████████████████▙           ",
	"        ▟█████████▛▀▀▜████████▙          ",
	"       ▟████████▛      ▜███████▙         ",
	"      ▟█████████        ████████▙        ",
	"     ▟██████████        █████▆▅▄▃▂       ",
	"    ▟██████████▛        ▜█████████▙      ",
	"   ▟██████▀▀▀              ▀▀██████▙     ",
	"  ▟███▀▘                       ❝▀███▙    ",
	" ▟▛▀                               ▀▜▙   ",
	NULL
};

const char *arch_ascii_classic[] = {
         "#00FFFF",
         "                   -`                    ",
         "                  .o+`                   ",
         "                 `ooo/                   ",
         "                `+oooo:                  ",
         "               `+oooooo:                 ",
         "               -+oooooo+:                ",
         "             `/:-:++oooo+:               ",
         "            `/++++/+++++++:              ",
         "           `/++++++++++++++:             ",
         "          `/+++ooooooooooooo/`           ",
        "         ./ooosssso++osssssso+`          ",
        "        .oossssso-````/ossssss+`         ",
        "       -osssssso.      :ssssssso.        ",
        "      :osssssss/        osssso+++.       ",
        "     /ossssssss/        +ssssooo/-       ",
        "   `/ossssso+/:-        -:/+osssso+-     ",
        "  `+sso+:-`                 `.-/+oso:    ",
        " `++:.                           `-/+/   ",
        " .`                                 `    ",
        NULL
};

const char *apple_ascii_mini[] = {
        "          .:'",
        "      __ :'__",
        "   .'`__`-'__``.",
        "  :__________.-'",
        "  :_________:",
        "   :_________`-;",
        "    `.__.-.__.'",
        NULL
};

const char *custom_ascii[] = {
        "#ff0000",
        " ",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "#000000ff",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        NULL
};

const char *custom2_ascii[] = {
        "#FFFF00",
        " ",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "#0000FF",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        "█████████████████████████████████",
        NULL
};

const char *fedora_ascii[] = {
	"#5094E2",
	"              .'ccccc:.             ",
	"         ,'ccccccccccccccc:.        ",
	"      .';cccccccccccccccccccc:.     ",
	"   .'cccccccccccccc",
	"#FFFFFF",
	"$o@@@@b",
	"#5094E2",
	"$ccccccc; ",
	"  .:ccccccccccccc",
	"#FFFFFF",
	"$d@@",
	"#5094E2",
	"$ccc",
	"#FFFFFF",
	"$q@@:",
	"#5094E2",
	"$cccccc, ",
	" .:ccccccccccccc",
	"#FFFFFF",
	"$@@@",
	"#5094E2",
	"$ccccc",
	"#FFFFFF",
	"$@@P",
	"#5094E2",
	"$ccccccc;",
	",:cccccccccccccc",
	"#FFFFFF",
	"$@@@",
	"#5094E2",
	"$ccccccccccccccc:",
	"ccccccccc",
	"#FFFFFF",
	"$o@@@@@",
	"#5094E2",
	"$c",
	"#FFFFFF",
	"$@@@@@@@",
	"#5094E2",
	"$ccccccccccc:",
	"ccccccc",
	"#FFFFFF",
	"$d@P",
	"#5094E2",
	"$cccccc",
	"#FFFFFF",
	"$@@@",
	"#5094E2",
	"$ccccccccccccccc:",
	"cccccc",
	"#FFFFFF",
	"$@@o",
	"#5094E2",
	"$ccccccc",
	"#FFFFFF",
	"$@@@",
	"#5094E2",
	"$ccccccccccccccc'",
	"cccccc",
	"#FFFFFF",
	"$q@@b",
	"#5094E2",
	"$ccccc",
	"#FFFFFF",
	"$@@@P",
	"#5094E2",
	"$ccccccccccccc;  ",
	"cccccccc",
	"#FFFFFF",
	"$q@@@@@@@P",
	"#5094E2",
	"$ccccccccccccc:,   ",
	"'cccccccccccccccccccccccccc:.      ",
	" ;ccccccccccccccccccccc:,.        ",
	NULL
};

const char *gentoo_ascii[] = {
        " ",
	"#FFC0CB",
	"         -/oyddmdhs+:.                 ",
	"     -o",
	"#8ABAD3",
	"$dNMMMMMMMMNNmhy+",
	"#FFC0CB",
	"$-`",
	"   -y",
	"#8ABAD3",
	"$NMMMMMMMMMMMNNNmmdhy",
	"#FFC0CB",
	"$+-",
	" `o",
	"#8ABAD3",
	"$mMMMMMMMMMMMMNmdmmmmddhhy",
	"#FFC0CB",
	"$/`",
	" om",
	"#8ABAD3",
	"$MMMMMMMMMMMN",
	"#FFC0CB",
	"$hhyyyo",
	"#8ABAD3",
	"$hmdddhhhd",
	"#FFC0CB",
	"$o`",
	".y",
	"#8ABAD3",
	"$dMMMMMMMMMMd",
	"#FFC0CB",
	"$hs++so/s",
	"#8ABAD3",
	"$mdddhhhhdm",
	"#FFC0CB",
	"$+`",
	" oy",
	"#8ABAD3",
	"$hdmNMMMMMMMN",
	"#FFC0CB",
	"$dyooy",
	"#8ABAD3",
	"$dmddddhhhhyhN",
	"#FFC0CB",
	"$d.",
	"  :o",
	"#8ABAD3",
	"$yhhdNNMMMMMMMNNNmmdddhhhhhyym",
	"#FFC0CB",
	"$Mh",
	"    .:",
	"#8ABAD3",
	"$+sydNMMMMMNNNmmmdddhhhhhhmM",
	"#FFC0CB",
	"$my",
	"       /m",
	"#8ABAD3",
	"$MMMMMMNNNmmmdddhhhhhmMNh",
	"#FFC0CB",
	"$s:",
	"    `o",
	"#8ABAD3",
	"$NMMMMMMMNNNmmmddddhhdmMNhs",
	"#FFC0CB",
	"$+`",
	"  `s",
	"#8ABAD3",
	"$NMMMMMMMMNNNmmmdddddmNMmhs",
	"#FFC0CB",
	"$/.",
	" /N",
	"#8ABAD3",
	"$MMMMMMMMNNNNmmmdddmNMNdso",
	"#FFC0CB",
	"$:`",
	"+M",
	"#8ABAD3",
	"$MMMMMMNNNNNmmmmdmNMNdso",
	"#FFC0CB",
	"$/-",
	"yM",
	"#8ABAD3",
	"$MNNNNNNNmmmmmNNMmhs+/",
	"#FFC0CB",
	"$-`",
	"/h",
	"#8ABAD3",
	"$MMNNNNNNNNMNdhs++/",
	"#FFC0CB",
	"$-`",
	" `/",
	"#8ABAD3",
	"$ohdmmddhys+++/:",
	"#FFC0CB",
	"$.`",
	"  `-//////:--.                        ",
	NULL
};

const char *tux_ascii[] = {
        "         _nnnn_        ",
        "        dGGGGMMb       ",
        "       @p~qp~~qMb      ",
        "       M|@||@) M|      ",
        "       @,----.JM|      ",
        "      JS^\\__/  qKL     ",
        "     dZP        qKRb   ",
        "    dZP          qKKb  ",
        "   fZP            SMMb ",
        "   HZM            MMMM ",
        "   FqM            MMMM ",
        " __| \".        |\\dS\"qML",
        " |    `.       | `' \\Zq",
        "_)      \\.___.,|     .'",
        "\\____   )MMMMMP|   .'  ",
        "     `-'       `--' hjm",
        NULL
};

const char *apple_ascii[] = {
        "#91E688",
        "                     ..'       ",
        "                 ,xNMM.        ",
        "               .OMMMMo         ",
        "               lMM\"           ",
        "     .;loddo:.  .olloddol;.    ",
        "   cKMMMMMMMMMMNWMMMMMMMMMM0:  ",
        "#f6ff96ff",
        " .KMMMMMMMMMMMMMMMMMMMMMMMWd.  ",
        " XMMMMMMMMMMMMMMMMMMMMMMMX.    ",
        "#eb9d99ff",
        ";MMMMMMMMMMMMMMMMMMMMMMMM:     ",
        ":MMMMMMMMMMMMMMMMMMMMMMMM:     ",
        ".MMMMMMMMMMMMMMMMMMMMMMMMX.   ",
        " kMMMMMMMMMMMMMMMMMMMMMMMMWd. ",
        "#D1A3BB",
        " 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
        "  'XMMMMMMMMMMMMMMMMMMMMMMMMK.",
        "#7da9dbff",
        "    kMMMMMMMMMMMMMMMMMMMMMMd  ",
        "     ;KMMMMMMMWXXWMMMMMMMk.   ",
        "       \"cooc*\"    \"*coo'\" ",
        NULL
};

const char *mint_ascii[] = {
	"#cececeff",
	"             ...-:::::-...",
	"          .-MMMMMMMMMMMMMMM-.",
	"      .-MMMM",
	"#87c800",
	"$..-:::::::-..",
	"#cececeff",
	"$MMMM-.",
	"    .:MMMM",
	"#87c800",
	"$.:MMMMMMMMMMMMMMM:.",
	"#cececeff",
	"$MMMM:.",
	"   -MMM",
	"#87c800",
	"$-M---MMMMMMMMMMMMMMMMMMM.",
	"#cececeff",
	"$MMM-",
	" `:MMM",
	"#87c800",
	"$:MM`  :MMMM:....::-...-MMMM:",
	"#cececeff",
	"$MMM:`",
	" :MMM",
	"#87c800",
	"$:MMM`  :MM:`  ``    ``  `:MMM:",
	"#cececeff",
	"$MMM:",
	".MMM",
	"#87c800",
	"$.MMMM`  :MM.  -MM.  .MM-  `MMMM.",
	"#cececeff",
	"$MMM.",
	":MMM",
	"#87c800",
	"$:MMMM`  :MM.  -MM-  .MM:  `MMMM-",
	"#cececeff",
	"$MMM:",
	":MMM",
	"#87c800",
	"$:MMMM`  :MM.  -MM-  .MM:  `MMMM:",
	"#cececeff",
	"$MMM:",
	":MMM",
	"#87c800",
	"$:MMMM`  :MM.  -MM-  .MM:  `MMMM-",
	"#cececeff",
	"$MMM:",
	".MMM",
	"#87c800",
	"$.MMMM`  :MM:--:MM:--:MM:  `MMMM.",
	"#cececeff",
	"$MMM.",
	" :MMM",
	"#87c800",
	"$:MMM-  `-MMMMMMMMMMMM-`  -MMM-",
	"#cececeff",
	"$MMM:",
	"  :MMM",
	"#87c800",
	"$:MMM:`                `:MMM:",
	"#cececeff",
	"$MMM:",
	"   .MMM",
	"#87c800",
	"$.MMMM:--------------:MMMM.",
	"#cececeff",
	"$MMM.",
	"     '-MMMM",
	"#87c800",
	"$.-MMMMMMMMMMMMMMM-.",
	"#cececeff",
	"$MMMM-'",
	"       '.-MMMM",
	"#87c800",
	"$``--:::::--``",
	"#cececeff",
	"$MMMM-.'",
	"#cececeff",
	"            '-MMMMMMMMMMMMM-'",
	"               ``-:::::-``",
	NULL
};

const char *slackware_ascii[] = {
	"#BFBFBF",
	"                  :::::::                   ",
	"            :::::::::::::::::::             ",
	"         :::::::::::::::::::::::::          ",
	"       ::::::::",
	"#989ef7",
	"$cllcccccllllllll",
	"#BFBFBF",
	"$::::::",
	"    :::::::::",
	"#989ef7", 
	"$lc               dc",
	"#BFBFBF",
	"$:::::::",
	"   ::::::::",
	"#989ef7",
	"$cl   clllccllll    oc",
	"#BFBFBF",
	"$:::::::::",
	"  :::::::::",
	"#989ef7",
	"$o   lc",
	"#BFBFBF",
	"$::::::::",
	"#989ef7",
	"$co   oc",
	"#BFBFBF",
	"$::::::::::",
	" ::::::::::",
	"#989ef7",
	"$o    cccclc",
	"#BFBFBF",
	"$:::::",
	"#989ef7",
	"$clcc",
	"#BFBFBF",
	"$::::::::::::",
	" :::::::::::",
	"#989ef7",
	"$lc        cclccclc",
	"#BFBFBF",
	"$:::::::::::::",
	"::::::::::::::",
	"#989ef7",
	"$lcclcc          lc",
	"#BFBFBF",
	"$::::::::::::",
	"::::::::::",
	"#989ef7",
	"$cclcc",
	"#BFBFBF",
	"$:::::",
	"#989ef7",
	"$lccclc     oc",
	"#BFBFBF",
	"$:::::::::::",
	"::::::::::",
	"#989ef7",
	"$o    l",
	"#BFBFBF",
	"$::::::::::",
	"#989ef7", 
	"$l    lc",
	"#BFBFBF",
	"$:::::::::::",
	" :::::",
	"#989ef7",
	"$cll",
	"#BFBFBF",
	"$:",
	"#989ef7", 
	"$o     clcllcccll     o",
	"#BFBFBF",
	"$:::::::::::",
	" :::::",
	"#989ef7",
	"$occ",
	"#BFBFBF",
	"$:",
	"#989ef7", 
	"$o                  clc",
	"#BFBFBF",
	"$:::::::::::",
	"  ::::",
	"#989ef7",
	"$ocl",
	"#BFBFBF",
	"$:",
	"#989ef7",
	"$ccslclccclclccclclc",
	"#BFBFBF",
	"$:::::::::::::",
	"   :::",
	"#989ef7",
	"$oclcccccccccccccllllllllllllll",
	"#BFBFBF",
	"$:::::",
	"    ::",
	"#989ef7",
	"$lcc1lcccccccccccccccccccccccco",
	"#BFBFBF",
	"$::::",
	"      ::::::::::::::::::::::::::::::::",
	"        ::::::::::::::::::::::::::::",
	"           ::::::::::::::::::::::",
	"                ::::::::::::",
	NULL
};

const char *debian_ascii[] = {
	"#FF0081",
	"       _,met$$$$$gg.",
	"    ,g$$$$$$$$$$$$$$$P.",
	"  ,g$$P\"        \"\"\"Y$$\".",
	" ,$$P'              `$$$.",
	"',$$P       ,ggs.     `$$b:",
	"`d$$'     ,$P\"'   ",
	"#FF0080",
	"$.",
	"#FF0081",
	"$    $$$",
	" $$P      d$'     ",
	"#FF0080",
	"$,",
	"#FF0081",
	"$    $$P",
	" $$:      $$.   ",
	"#FF0080",
	"$-",
	"#FF0081",
	"$    ,d$$'",
	" $$;      Y$b._   _,d$P'",
	" Y$$.    ",
	"#FF0080",
	"$.",
	"#FF0081",
	"$\"Y$$$$P\"'",
	" `$$b      ",
	"#FF0081",
	"$\"-.__",
	"#FF0081",
	"$",
	"  `Y$$",
	"   `Y$$.",
	"     `$$b.",
	"       `Y$$b.",
	"          `\"Y$b._",
	"              `\"\"\"",
	NULL
};