#define _POSIX_C_SOURCE 200809L
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ascii.h"
#include <glob.h>
#include <unistd.h>
#include <pwd.h>
#include <sys/utsname.h>
#include <sys/statvfs.h>

/* Files includes. */
#include "fetch_sw.h"
#include "utils.h"
#include "ascii_gen.h"
#include "config.h"

#define MAX_ASCII_FILE_LINES            1000
#define MAX_ASCII_FILE_LINE_LENGTH      512

int main(int argc, char *argv[])
{
	struct cfetch_cfg cfg;
	char *distro;
	const char **art = NULL;

	cfg_init_defaults(&cfg);
	cfg_load(&cfg);

	distro = get_distro();

	if (argc >= 3 && strcmp(argv[1], "--ExportAscii") == 0) {
		const char *filename = argv[2];
		printf("// Generated by cfetch --ExportAscii %s\n", filename);
		printf("// Insert this code into your C:\n\n");
		{
			int rc = export_ascii_art(filename);
			if (distro)
				free(distro);
			cfg_free(&cfg);
			return rc;
		}
	}

	if (argc == 1) {
		art = select_art_by_name(cfg.ascii_art, distro);
		print_ascii_configured(art, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--arch") == 0) {
		print_ascii_configured((const char **)arch_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--arch-classic") == 0) {
		print_ascii_configured((const char **)arch_ascii_classic, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--redhat") == 0) {
		print_ascii_configured((const char **)redhat_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--apple-mini") == 0) {
		print_ascii_configured((const char **)apple_ascii_mini, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--custom") == 0) {
		print_ascii_configured((const char **)custom_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--fedora") == 0) {
		print_ascii_configured((const char **)fedora_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--gentoo") == 0) {
		print_ascii_configured((const char **)gentoo_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--tux") == 0) {
		print_ascii_configured((const char **)tux_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--apple") == 0) {
		print_ascii_configured((const char **)apple_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--mint") == 0) {
		print_ascii_configured((const char **)mint_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--slackware") == 0) {
		print_ascii_configured((const char **)slackware_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--debian") == 0) {
		print_ascii_configured((const char **)debian_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--arch-alt") == 0) {
		print_ascii_configured((const char **)arch_ascii_alt, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--dota") == 0) {
		print_ascii_configured((const char **)dota_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--nixos") == 0) {
		print_ascii_configured((const char **)nixos_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--endeavour") == 0) {
		print_ascii_configured((const char **)endeavour_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--void") == 0) {
		print_ascii_configured((const char **)void_ascii, &cfg);
	} else if (argc == 2 && strcmp(argv[1], "--saturn") == 0) {
		print_ascii_configured((const char **)saturn_ascii, &cfg);
	} else {
		fprintf(stderr, "Error: Invalid arguments.\n");
		fprintf(stderr, "Usage: %s [no args -> config ascii_art] or flags: --arch | --redhat | --apple-mini | --fedora | --gentoo | --tux | --apple | --mint | --slackware | --debian | --arch-alt | --dota | --nixos | --ExportAscii <filename>\n", argv[0]);
		cfg_free(&cfg);
		if (distro) free(distro);
		return 1;
	}

	if (distro != NULL)
		free(distro);
	cfg_free(&cfg);
	return 0;
}